version: '3'

services:
  mariadb-nextcloud:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - mariadb-nextcloud:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:latest
    ports:
      - 8084:80
    links:
      - mariadb-nextcloud
      - redis
    volumes:
      - ./nextcloud:/var/www/html
    restart: always

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data 

volumes:
  mariadb-nextcloud:
  redis:
